---
title: "Analysis of News Articles"
author: " "
date: ""
output:
  html_notebook: default
  pdf_document:
    latex_engine: xelatex
mainfont: Helvetica
monofont: Monaco
---

a)Abstract. This should consist of concise statements of the aims, methods, results, 
and conclusions (eg, 200-300 words).


b)Introduction. Include a clear statement of the aims and questions to be addressed. 
The goal of the analyses should be clear from the introduction. You may include 
background material, such as previous research that your analysis builds on, but this 
should be kept brief.

c)Data Set Description. Describe the data set, including the source of the data, data 
collection methods, study design (e.g., randomized experiment, observational data, 
survey, etc.)

**Source** :
We downloaded this data from UCI machine learning repository.The link for the source is mentioned below:

**https://archive.ics.uci.edu/ml/datasets/online+news+popularity**

This data set summarizes a heterogeneous set of features about articles published by Mashable (www.mashable.com)  in a period of two years. Some of the general characteristics of this data set are mentioned below:

Data Set Characteristics: Multivariate
Attribute Characteristics: Integer, Real
Number of Instances: 39797
Number of Attributes: 61
Missing Values?: No missing values
------------need to add the stuff here (the actual number of attributes and stuff).--------------

Attribute Information:


d)Statistical Methods. Describe the statistical methods used for the analysis, 
including discussion of underlying assumptions and explanation for why the 
methodology you used is appropriate. State the software used as well as any special 
packages or user-written programs as needed. Code should not be included.

Before diving in deep for the Statistical Methods, we have bifurcated our statistical analysis into two parts:

Descriptive statistics:

Using the principles of graphical excellence and graphical integrity, we have used EDA (exploratory data analysis ) to answer the question:
**How do linguistic features vary across different article categories?**

The above question will be applied to each of the following linguistic features one at a time across article category (business, lifestyle, entertainment, technology, world social media; applies for all questions using article category)

-- How many words are there in an article?
-- How many words are there in an title of an article?
-- What is an average token length in an article?
-- How is the polarity of articles distributed within a range of [-1 to 1]?
-- How is article subjectivity varying with objective and subjective statements?
-- 

**Inferential statistics:**

Using the power of inferential statistics, the NULL hypothesis and alternative hypothesis under consideration is as:

**NULL HYPOTHESIS:**

Using a linear regression model, understand what is the effect of different variables on the number of shares for an article? 

**ALTERNATIVE HYPOTHESIS:**


Assumptions made in the linear regression:
-- Independence: The data points (observations) represents individual articles without any stratifcation and hence the independence assumption holds good here in our case.
-- Constant variance: **-------------------------?????**
-- Linearity: **-------------------------?????**
-- Normality: From the QQ plot, the normality assumption does not holds good. But since there are large number of data points, the assumption of normality to hold true holds good.


e)Results. Describe your results clearly and concisely. Use graphical displays and 
tables to convey descriptive information about the data and the results of the 
analysis. 


f)Discussion. This section should briefly summarize the results and conclusions. Also 
describe limitations of the analyses, including limitations of the data set as well as 
of the statistical analyses.


g)References. List books or articles you consulted. (It is not necessary to do a lot of 
background research, so the reference list should be short.) References for statistical 
methods used in class (e.g., t-tests, and linear regression) are not required, but 
references should be given for advanced methods not covered in class.

h)Tables and Figures. These can be included with the text in the body of the report 
or in a separate section at the end. All should have clear titles/captions.


i)Appendices. You may include more technical aspects of your analysis in an 
appendix if it will help with the readability of the main body of your report. 
Appendices are included in the 20-page limit.